head.load(
    { file: 'libs/jquery/dist/jquery-2.1.3.js' },
    { file: 'libs/bootstrap/dist/css/bootstrap.css' },
    { file: 'libs/bootstrap/dist/js/bootstrap.js' },
    { file: 'libs/font-awesome/css/font-awesome.css' },
    { file: 'libs/angular/angular.js' },
    { file: 'libs/angular/angular-route.js' },
    { file: 'libs/angular/angular-animate.js' },
    { file: 'libs/angular/angular-touch.js' },
    { file: 'libs/angular/angular-sanitize.js' },
    { file: 'libs/angular-bootstrap/ui-bootstrap-tpls.js' },  
    { file: 'libs/jquery.poshytip.min.js' }, 
    { file: 'tableFixed.js' },
    { file: 'style.css' },
    { file: 'tableFixedStyle.css' },
    { file: 'libs/moment.js' },
    { file: 'selfscan/S2M.js' },
    { file: 'selfscan/app/app.js' },
    { file: 'selfscan/app/controllers/MainController.js' },
    { file: 'selfscan/booklist/Booklist.js' },
    { file: 'selfscan/booklist/controllers/BooklistController.js' },
    { file: 'selfscan/user/User.js' },
    { file: 'selfscan/user/controllers/UserController.js' },
    { file: 'selfscan/restore/Restore.js' },
    { file: 'selfscan/restore/controllers/RestoreController.js' }
);
